# Plots for Logistic Distributions Project
# Note: Functions in other files need to be run first because these plots call other functions

############################################
  # General Logistic Distribution Plots #
############################################

# plot of the logistic distribution against the normal distribution (CDF and pdf)
pdf(file="logistic-normal.pdf",width=12,height=6)
par(mfrow=c(1,2),mgp = c(1.8, .7, 0),cex.axis=1,cex.lab=1.5,cex.main=2)
x <- seq(-5,5, length=100)
hx <- dlogis(x)
plot(x, hx, type="l", xlab="",
     ylab="Density", main="Probability Density")
par(new=TRUE)
x <- seq(-5,5, length=100)
hx <- dnorm(x)
plot(x, hx, col="red", bty = 'n',type="l", ann = FALSE, xaxt = 'n', yaxt = 'n')
x <- seq(-5,5, length=100)
hx <- plogis(x)
plot(x, hx, type="l", xlab="",
     ylab="", main="Cumulative Distribution")
par(new=TRUE)
x <- seq(-5,5, length=100)
hx <- pnorm(x)
plot(x, hx, col="red", bty = 'n',type="l", ann = FALSE, xaxt = 'n', yaxt = 'n')
legend("bottomright",c("Normal","Logistic"), 
       cex=1.5, col=c("red","black"), lwd=c(1,1))
dev.off()

# plot of the logistic distribution with different parameters (CDF and pdf)
pdf("different-parameters.pdf",width=12,height=6)
par(mfrow=c(1,2),mgp = c(1.8, .7, 0),cex.axis=1,cex.lab=1.5,cex.main=2)
x <- seq(-5,20, length=100)
plot(c(-5, 20), c(0, 0.27), xlab = '', ylab = '', main = "Probability Density Function", type = "n")
lines(x, dlogis(x,2,1), lwd = 1, col = "green")
lines(x, dlogis(x,5,2), lwd = 1, col = "red")
lines(x, dlogis(x,7,3), lwd = 1, col = "blue")
lines(x, dlogis(x,9,4), lwd = 1, col = "purple")
x <- seq(-5,20, length=100)
plot(x, plogis(x,2,1), col="green", type="l", xlab="",ylab="", main="Cumulative Function")
par(new=TRUE)
plot(x, plogis(x,5,2), col="red", bty = 'n',type="l", ann = FALSE, xaxt = 'n', yaxt = 'n')
par(new=TRUE)
plot(x, plogis(x,7,2), col="blue", bty = 'n',type="l", ann = FALSE, xaxt = 'n', yaxt = 'n')
par(new=TRUE)
plot(x, plogis(x,9,4), col="purple", bty = 'n',type="l", ann = FALSE, xaxt = 'n', yaxt = 'n')
legend("bottomright",c(expression(paste(mu, "=2, ", beta,"=1")),expression(paste(mu, "=5, ", beta,"=2")),
                        expression(paste(mu, "=7, ", beta,"=3")),expression(paste(mu, "=9, ", beta,"=4"))), 
       cex=1.5, col=c("green","red","blue","purple"), lwd=c(1,1,1,1))
dev.off()

############################################
      # Plots for Simulation Study #
############################################

##### Plots for Simulation with mu=5,beta=5 #####
xaxis <- c(100,500,1000)
pdf("sim-parameter-mu-55.pdf",width=12,height=6)
par(mfrow=c(1,2),mgp = c(1.8, .7, 0),cex.axis=1,cex.lab=1.5,cex.main=2,omi = c(0, 0, .3, 0))
plot(xaxis,c(-.55,0,.55),type="n",xaxt = 'n',ylab="Bias",xlab="N",main=expression(paste("Bias of ", mu)))
points(xaxis,c(bias.mle.mean.5.5[1,2],bias.mle.mean.5.5[2,2],bias.mle.mean.5.5[3,2]),pch=18, type="o", lty=2,col='purple')
points(xaxis,c(bias.mom.mean.5.5[1,2],bias.mom.mean.5.5[2,2],bias.mom.mean.5.5[3,2]),pch=15, type="o", lty=2,col='blue')
points(xaxis,c(bias.bayes.mean.5.5[1,2],bias.bayes.mean.5.5[2,2],bias.bayes.mean.5.5[3,2]),pch=17, type="o", lty=2,col='red',bty = 'n', ann = FALSE, xaxt = 'n', yaxt = 'n')
abline(h=0)
ticks<-c(100,500,1000)
axis(1,at=ticks,labels=ticks)

plot(xaxis,c(0,0.5,1.2),type="n",xaxt = 'n',ylab="MSE",xlab="N",main=expression(paste("MSE of ", mu)))
points(xaxis,c(bias.mle.mean.5.5[1,3],bias.mle.mean.5.5[2,3],bias.mle.mean.5.5[3,3]),pch=18,type="o", lty=2,col='purple',bty = 'n', ann = FALSE, xaxt = 'n', yaxt = 'n')
points(xaxis,c(bias.mom.mean.5.5[1,3],bias.mom.mean.5.5[2,3],bias.mom.mean.5.5[3,3]),pch=15,type="o", lty=2,col='blue',bty = 'n', ann = FALSE, xaxt = 'n', yaxt = 'n')
points(xaxis,c(bias.bayes.mean.5.5[1,3],bias.bayes.mean.5.5[2,3],bias.bayes.mean.5.5[3,3]),pch=17,type="o", lty=2,col='red',bty = 'n', ann = FALSE, xaxt = 'n', yaxt = 'n')
ticks<-c(100,500,1000)
axis(1,at=ticks,labels=ticks)
legend("topright",c("MOM","MLE","Bayes"), cex=1.3, col=c("blue","purple","red"),lty=c(2,2,2),
       pch=c(18,15,17), lwd=c(1,1,1))
title(main = expression(paste("Estimator performance for ", mu, " when ", mu, "=5, ", beta,"=5")), outer = TRUE)
dev.off()

pdf("sim-parameter-beta-55.pdf",width=12,height=6)
par(mfrow=c(1,2),mgp = c(1.8, .7, 0),cex.axis=1,cex.lab=1.5,cex.main=2,omi = c(0, 0, .3, 0))
plot(xaxis,c(-0.3,0,0.3),type="n",xaxt = 'n',ylab="Bias",xlab="N",main=expression(paste("Bias of ", beta)))
points(xaxis,c(bias.mle.mean.5.5[1,4],bias.mle.mean.5.5[2,4],bias.mle.mean.5.5[3,4]),pch=18,type="o", lty=2,col='purple',bty = 'n', ann = FALSE, xaxt = 'n', yaxt = 'n')
points(xaxis,c(bias.mom.mean.5.5[1,4],bias.mom.mean.5.5[2,4],bias.mom.mean.5.5[3,4]),pch=15,type="o", lty=2,col='blue',bty = 'n', ann = FALSE, xaxt = 'n', yaxt = 'n')
points(xaxis,c(bias.bayes.mean.5.5[1,4],bias.bayes.mean.5.5[2,4],bias.bayes.mean.5.5[3,4]),pch=17,type="o", lty=2,col='red',bty = 'n', ann = FALSE, xaxt = 'n', yaxt = 'n')
abline(h=0)
ticks<-c(100,500,1000)
axis(1,at=ticks,labels=ticks)

plot(xaxis,c(0,0.1,0.25),type="n",xaxt = 'n',ylab="MSE",xlab="N",main=expression(paste("MSE of ", beta)))
points(xaxis,c(bias.mle.mean.5.5[1,5],bias.mle.mean.5.5[2,5],bias.mle.mean.5.5[3,5]),pch=18,type="o", lty=2,col='purple',bty = 'n', ann = FALSE, xaxt = 'n', yaxt = 'n')
points(xaxis,c(bias.mom.mean.5.5[1,5],bias.mom.mean.5.5[2,5],bias.mom.mean.5.5[3,5]),pch=15,type="o", lty=2,col='blue',bty = 'n', ann = FALSE, xaxt = 'n', yaxt = 'n')
points(xaxis,c(bias.bayes.mean.5.5[1,5],bias.bayes.mean.5.5[2,5],bias.bayes.mean.5.5[3,5]),pch=17,type="o", lty=2,col='red',bty = 'n', ann = FALSE, xaxt = 'n', yaxt = 'n')
ticks<-c(100,500,1000)
axis(1,at=ticks,labels=ticks)
legend("topright",c("MOM","MLE","Bayes"), cex=1.3, col=c("blue","purple","red"),lty=c(2,2,2),
       pch=c(18,15,17), lwd=c(1,1,1))
title(main = expression(paste("Estimator performance for ", beta, " when ", mu, "=5, ", beta,"=5")), outer = TRUE)
dev.off()


##### Plots for Simulation with mu=20,beta=5 #####
xaxis <- c(100,500,1000)
pdf("sim-parameter-mu-205.pdf",width=12,height=6)
par(mfrow=c(1,2),mgp = c(1.8, .7, 0),cex.axis=1,cex.lab=1.5,cex.main=2,omi = c(0, 0, .3, 0))
plot(xaxis,c(-0.55,0,0.55),type="n",xaxt = 'n',ylab="Bias",xlab="N",main=expression(paste("Bias of ", mu)))
points(xaxis,c(bias.mle.mean.20.5[1,2],bias.mle.mean.20.5[2,2],bias.mle.mean.20.5[3,2]),pch=18,type="o", lty=2,col='purple',bty = 'n', ann = FALSE, xaxt = 'n', yaxt = 'n')
points(xaxis,c(bias.mom.mean.20.5[1,2],bias.mom.mean.20.5[2,2],bias.mom.mean.20.5[3,2]),pch=15,type="o", lty=2,col='blue',bty = 'n', ann = FALSE, xaxt = 'n', yaxt = 'n')
points(xaxis,c(bias.bayes.mean.20.5[1,2],bias.bayes.mean.20.5[2,2],bias.bayes.mean.20.5[3,2]),pch=17,type="o", lty=2,col='red',bty = 'n', ann = FALSE, xaxt = 'n', yaxt = 'n')
abline(h=0)
ticks<-c(100,500,1000)
axis(1,at=ticks,labels=ticks)

plot(xaxis,c(0,0.4,0.85),type="n",xaxt = 'n',ylab="MSE",xlab="N",main=expression(paste("MSE of ", mu)))
points(xaxis,c(bias.mle.mean.20.5[1,3],bias.mle.mean.20.5[2,3],bias.mle.mean.20.5[3,3]),pch=18,type="o", lty=2,col='purple',bty = 'n', ann = FALSE, xaxt = 'n', yaxt = 'n')
points(xaxis,c(bias.mom.mean.20.5[1,3],bias.mom.mean.20.5[2,3],bias.mom.mean.20.5[3,3]),pch=15,type="o", lty=2,col='blue',bty = 'n', ann = FALSE, xaxt = 'n', yaxt = 'n')
points(xaxis,c(bias.bayes.mean.20.5[1,3],bias.bayes.mean.20.5[2,3],bias.bayes.mean.20.5[3,3]),pch=17,type="o", lty=2,col='red',bty = 'n', ann = FALSE, xaxt = 'n', yaxt = 'n')
ticks<-c(100,500,1000)
axis(1,at=ticks,labels=ticks)
legend("topright",c("MOM","MLE","Bayes"), cex=1.3, col=c("blue","purple","red"),lty=c(2,2,2),
       pch=c(18,15,17), lwd=c(1,1,1))
title(main = expression(paste("Estimator performance for ", mu, " when ", mu, "=20, ", beta,"=5")), outer = TRUE)
dev.off()

pdf("sim-parameter-beta-205.pdf",width=12,height=6)
par(mfrow=c(1,2),mgp = c(1.8, .7, 0),cex.axis=1,cex.lab=1.5,cex.main=2,omi = c(0, 0, .3, 0))
plot(xaxis,c(-0.10,0,0.10),type="n",xaxt = 'n',ylab="Bias",xlab="N",main=expression(paste("Bias of ", beta)))
points(xaxis,c(bias.mle.mean.20.5[1,4],bias.mle.mean.20.5[2,4],bias.mle.mean.20.5[3,4]),pch=18,type="o", lty=2,col='purple',bty = 'n', ann = FALSE, xaxt = 'n', yaxt = 'n')
points(xaxis,c(bias.mom.mean.20.5[1,4],bias.mom.mean.20.5[2,4],bias.mom.mean.20.5[3,4]),pch=15,type="o", lty=2,col='blue',bty = 'n', ann = FALSE, xaxt = 'n', yaxt = 'n')
points(xaxis,c(bias.bayes.mean.20.5[1,4],bias.bayes.mean.20.5[2,4],bias.bayes.mean.20.5[3,4]),pch=17,type="o", lty=2,col='red',bty = 'n', ann = FALSE, xaxt = 'n', yaxt = 'n')
abline(h=0)
ticks<-c(100,500,1000)
axis(1,at=ticks,labels=ticks)

plot(xaxis,c(0,0.10,0.20),type="n",xaxt = 'n',ylab="MSE",xlab="N",main=expression(paste("MSE of ", beta)))
points(xaxis,c(bias.mle.mean.20.5[1,5],bias.mle.mean.20.5[2,5],bias.mle.mean.20.5[3,5]),pch=18,type="o", lty=2,col='purple',bty = 'n', ann = FALSE, xaxt = 'n', yaxt = 'n')
points(xaxis,c(bias.mom.mean.20.5[1,5],bias.mom.mean.20.5[2,5],bias.mom.mean.20.5[3,5]),pch=15,type="o", lty=2,col='blue',bty = 'n', ann = FALSE, xaxt = 'n', yaxt = 'n')
points(xaxis,c(bias.bayes.mean.20.5[1,5],bias.bayes.mean.20.5[2,5],bias.bayes.mean.20.5[3,5]),pch=17,type="o", lty=2,col='red',bty = 'n', ann = FALSE, xaxt = 'n', yaxt = 'n')
ticks<-c(100,500,1000)
axis(1,at=ticks,labels=ticks)
legend("topright",c("MOM","MLE","Bayes"), cex=1.3, col=c("blue","purple","red"),lty=c(2,2,2),
       pch=c(18,15,17), lwd=c(1,1,1))
title(main = expression(paste("Estimator performance for ", beta, " when ", mu, "=20, ", beta,"=5")), outer = TRUE)
dev.off()


##### Plots for Simulation with mu=50,beta=20 #####
xaxis <- c(100,500,1000)
pdf("sim-parameter-mu-5020.pdf",width=12,height=6)
par(mfrow=c(1,2),mgp = c(1.8, .7, 0),cex.axis=1,cex.lab=1.5,cex.main=2,omi = c(0, 0, .3, 0))
plot(xaxis,c(-17,0,5),type="n",xaxt = 'n',ylab="Bias",xlab="N",main=expression(paste("Bias of ", mu)))
points(xaxis,c(bias.mle.mean.50.20[1,2],bias.mle.mean.50.20[2,2],bias.mle.mean.50.20[3,2]), pch=18,type="o", lty=2,col='purple',bty = 'n', ann = FALSE, xaxt = 'n', yaxt = 'n')
points(xaxis,c(bias.mom.mean.50.20[1,2],bias.mom.mean.50.20[2,2],bias.mom.mean.50.20[3,2]),pch=15,type="o", lty=2,col='blue',bty = 'n', ann = FALSE, xaxt = 'n', yaxt = 'n')
points(xaxis,c(bias.bayes.mean.50.20[1,2],bias.bayes.mean.50.20[2,2],bias.bayes.mean.50.20[3,2]),pch=17,type="o", lty=2,col='red',bty = 'n', ann = FALSE, xaxt = 'n', yaxt = 'n')
abline(h=0)
ticks<-c(100,500,1000)
axis(1,at=ticks,labels=ticks)
plot(xaxis,c(0,100,282),type="n",xaxt = 'n',ylab="MSE",xlab="N",main=expression(paste("MSE of ", mu)))
points(xaxis,c(bias.mle.mean.50.20[1,3],bias.mle.mean.50.20[2,3],bias.mle.mean.50.20[3,3]),pch=18,type="o", lty=2,col='purple',bty = 'n', ann = FALSE, xaxt = 'n', yaxt = 'n')
points(xaxis,c(bias.mom.mean.50.20[1,3],bias.mom.mean.50.20[2,3],bias.mom.mean.50.20[3,3]),pch=15,type="o", lty=2,col='blue',bty = 'n', ann = FALSE, xaxt = 'n', yaxt = 'n')
points(xaxis,c(bias.bayes.mean.50.20[1,3],bias.bayes.mean.50.20[2,3],bias.bayes.mean.50.20[3,3]),pch=17,type="o", lty=2,col='red',bty = 'n', ann = FALSE, xaxt = 'n', yaxt = 'n')
ticks<-c(100,500,1000)
axis(1,at=ticks,labels=ticks)
legend("topright",c("MOM","MLE","Bayes"), cex=1.3, col=c("blue","purple","red"),lty=c(2,2,2),
       pch=c(18,15,17), lwd=c(1,1,1))
title(main = expression(paste("Estimator performance for ", mu, " when ", mu, "=50, ", beta,"=20")), outer = TRUE)
dev.off()

pdf("sim-parameter-beta-5020.pdf",width=12,height=6)
par(mfrow=c(1,2),mgp = c(1.8, .7, 0),cex.axis=1,cex.lab=1.5,cex.main=2,omi = c(0, 0, .3, 0))
plot(xaxis,c(-0.90,0,0.10),type="n",xaxt = 'n',ylab="Bias",xlab="N",main=expression(paste("Bias of ", beta)))
points(xaxis,c(bias.mle.mean.50.20[1,4],bias.mle.mean.50.20[2,4],bias.mle.mean.50.20[3,4]),pch=18,type="o", lty=2,col='purple',bty = 'n', ann = FALSE, xaxt = 'n', yaxt = 'n')
points(xaxis,c(bias.mom.mean.50.20[1,4],bias.mom.mean.50.20[2,4],bias.mom.mean.50.20[3,4]),pch=15,type="o", lty=2,col='blue',bty = 'n', ann = FALSE, xaxt = 'n', yaxt = 'n')
points(xaxis,c(bias.bayes.mean.50.20[1,4],bias.bayes.mean.50.20[2,4],bias.bayes.mean.50.20[3,4]),pch=17,type="o", lty=2,col='red',bty = 'n', ann = FALSE, xaxt = 'n', yaxt = 'n')
abline(h=0)
ticks<-c(100,500,1000)
axis(1,at=ticks,labels=ticks)
plot(xaxis,c(0,0.05,3.5),type="n",xaxt = 'n',ylab="MSE",xlab="N",main=expression(paste("MSE of ", beta)))
points(xaxis,c(bias.mle.mean.50.20[1,5],bias.mle.mean.50.20[2,5],bias.mle.mean.50.20[3,5]),pch=18,type="o", lty=2,col='purple',bty = 'n', ann = FALSE, xaxt = 'n', yaxt = 'n')
points(xaxis,c(bias.mom.mean.50.20[1,5],bias.mom.mean.50.20[2,5],bias.mom.mean.50.20[3,5]),pch=15,type="o", lty=2,col='blue',bty = 'n', ann = FALSE, xaxt = 'n', yaxt = 'n')
points(xaxis,c(bias.bayes.mean.50.20[1,5],bias.bayes.mean.50.20[2,5],bias.bayes.mean.50.20[3,5]),pch=17,type="o", lty=2,col='red',bty = 'n', ann = FALSE, xaxt = 'n', yaxt = 'n')
ticks<-c(100,500,1000)
axis(1,at=ticks,labels=ticks)
legend("topright",c("MOM","MLE","Bayes"), cex=1.3, col=c("blue","purple","red"),lty=c(2,2,2),
       pch=c(18,15,17), lwd=c(1,1,1))
title(main = expression(paste("Estimator performance for ", beta, " when ", mu, "=50, ", beta,"=20")), outer = TRUE)
dev.off()


##### Plots for Simulation with mu=100,beta=10 #####
xaxis <- c(100,500,1000)
pdf("sim-parameter-mu-10010.pdf",width=12,height=6)
par(mfrow=c(1,2),mgp = c(1.8, .7, 0),cex.axis=1,cex.lab=1.5,cex.main=2,omi = c(0, 0, .3, 0))
plot(xaxis,c(-2,0,0.10),type="n",xaxt = 'n',ylab="Bias",xlab="N",main=expression(paste("Bias of ", mu)))
points(xaxis,c(bias.mle.mean.100.10[1,2],bias.mle.mean.100.10[2,2],bias.mle.mean.100.10[3,2]),pch=18,type="o", lty=2,col='purple',bty = 'n', ann = FALSE, xaxt = 'n', yaxt = 'n')
points(xaxis,c(bias.mom.mean.100.10[1,2],bias.mom.mean.100.10[2,2],bias.mom.mean.100.10[3,2]),pch=15,type="o", lty=2,col='blue',bty = 'n', ann = FALSE, xaxt = 'n', yaxt = 'n')
points(xaxis,c(bias.bayes.mean.100.10[1,2],bias.bayes.mean.100.10[2,2],bias.bayes.mean.100.10[3,2]),pch=17,type="o", lty=2,col='red',bty = 'n', ann = FALSE, xaxt = 'n', yaxt = 'n')
abline(h=0)
ticks<-c(100,500,1000)
axis(1,at=ticks,labels=ticks)
plot(xaxis,c(0,0.05,6),type="n",xaxt = 'n',ylab="MSE",xlab="N",main=expression(paste("MSE of ", mu)))
points(xaxis,c(bias.mle.mean.100.10[1,3],bias.mle.mean.100.10[2,3],bias.mle.mean.100.10[3,3]),pch=18,type="o", lty=2,col='purple',bty = 'n', ann = FALSE, xaxt = 'n', yaxt = 'n')
points(xaxis,c(bias.mom.mean.100.10[1,3],bias.mom.mean.100.10[2,3],bias.mom.mean.100.10[3,3]),pch=15,type="o", lty=2,col='blue',bty = 'n', ann = FALSE, xaxt = 'n', yaxt = 'n')
points(xaxis,c(bias.bayes.mean.100.10[1,3],bias.bayes.mean.100.10[2,3],bias.bayes.mean.100.10[3,3]),pch=17,type="o", lty=2,col='red',bty = 'n', ann = FALSE, xaxt = 'n', yaxt = 'n')
ticks<-c(100,500,1000)
axis(1,at=ticks,labels=ticks)
legend("topright",c("MOM","MLE","Bayes"), cex=1.3, col=c("blue","purple","red"),lty=c(2,2,2),
       pch=c(18,15,17), lwd=c(1,1,1))
title(main = expression(paste("Estimator performance for ", mu, " when ", mu, "=100, ", beta,"=10")), outer = TRUE)
dev.off()

pdf("sim-parameter-beta-10010.pdf",width=12,height=6)
par(mfrow=c(1,2),mgp = c(1.8, .7, 0),cex.axis=1,cex.lab=1.5,cex.main=2,omi = c(0, 0, .3, 0))
plot(xaxis,c(-1.5,0,0.10),type="n",xaxt = 'n',ylab="Bias",xlab="N",main=expression(paste("Bias of ", beta)))
points(xaxis,c(bias.mle.mean.100.10[1,4],bias.mle.mean.100.10[2,4],bias.mle.mean.100.10[3,4]),pch=18,type="o", lty=2,col='purple',bty = 'n', ann = FALSE, xaxt = 'n', yaxt = 'n')
points(xaxis,c(bias.mom.mean.100.10[1,4],bias.mom.mean.100.10[2,4],bias.mom.mean.100.10[3,4]),pch=15,type="o", lty=2,col='blue',bty = 'n', ann = FALSE, xaxt = 'n', yaxt = 'n')
points(xaxis,c(bias.bayes.mean.100.10[1,4],bias.bayes.mean.100.10[2,4],bias.bayes.mean.100.10[3,4]),pch=17,type="o", lty=2,col='red',bty = 'n', ann = FALSE, xaxt = 'n', yaxt = 'n')
abline(h=0)
ticks<-c(100,500,1000)
axis(1,at=ticks,labels=ticks)
plot(xaxis,c(0,0.05,2),type="n",xaxt = 'n',ylab="MSE",xlab="N",main=expression(paste("MSE of ", beta)))
points(xaxis,c(bias.mle.mean.100.10[1,5],bias.mle.mean.100.10[2,5],bias.mle.mean.100.10[3,5]),pch=18,type="o", lty=2,col='purple',bty = 'n', ann = FALSE, xaxt = 'n', yaxt = 'n')
points(xaxis,c(bias.mom.mean.100.10[1,5],bias.mom.mean.100.10[2,5],bias.mom.mean.100.10[3,5]),pch=15,type="o", lty=2,col='blue',bty = 'n', ann = FALSE, xaxt = 'n', yaxt = 'n')
points(xaxis,c(bias.bayes.mean.100.10[1,5],bias.bayes.mean.100.10[2,5],bias.bayes.mean.100.10[3,5]),pch=17,type="o", lty=2,col='red',bty = 'n', ann = FALSE, xaxt = 'n', yaxt = 'n')
ticks<-c(100,500,1000)
axis(1,at=ticks,labels=ticks)
legend("topright",c("MOM","MLE","Bayes"), cex=1.3, col=c("blue","purple","red"),lty=c(2,2,2),
       pch=c(18,15,17), lwd=c(1,1,1))
title(main = expression(paste("Estimator performance for ", beta, " when ", mu, "=100, ", beta,"=10")), outer = TRUE)
dev.off()
